services:
  dev-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "4000:4000"  
    working_dir: /app
   

    command: bash /app/debug.sh


      