services:
  dev-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"  
    working_dir: /app
   
    command: bash /app/backend.sh

      